### ISSUE TITLE
Issue with duplicating Menu_Item_Custom_Fields_Walker via wp-menu-icons plugin

### ISSUE THREAD

**Issue by vburlak** [kucrut/wp-menu-item-custom-fields#5]
Hi @kucrut again.

I'm using your brilliant plugin `wp-menu-icons` together with your `wp-menu-item-custom-fields` library for adding my own menu item custom fields.

I required `Menu_Item_Custom_Fields_Walker` from `wp-menu-item-custom-fields` library directly in my theme and extended with some extra functions for my needs.
So, when my theme activated within `wp-menu-icons` plugin — i can't use my functions from my theme's `Menu_Item_Custom_Fields_Walker`, because class is already exist in menu icons plugin.

For example, here is my `Menu_Item_Custom_Fields_Walker` where I adding my own `item-controls` in `.menu-item-bar`.

```php
class Menu_Item_Custom_Fields_Walker extends Walker_Nav_Menu_Edit {

	function start_el( &$output, $item, $depth = 0, $args = array(), $id = 0 ) {
		$item_output = '';
		parent::start_el( $item_output, $item, $depth, $args, $id );
		$output_pre = preg_replace(
			// NOTE: Check this regex from time to time!
			'/(?=<span[^>]+class="[^"]*item-type)/',
			$this->get_labels( $item, $depth, $args ),
			$item_output
		);
		$output .= preg_replace(
			// NOTE: Check this regex from time to time!
			'/(?=<p[^>]+class="[^"]*field-move)/',
			$this->get_fields( $item, $depth, $args ),
			$output_pre
		);
	}

	protected function get_fields( $item, $depth, $args = array(), $id = 0 ) {
		ob_start();
		do_action( 'wp_nav_menu_item_custom_fields', $id, $item, $depth, $args );
		return ob_get_clean();
	}

	protected function get_labels( $item, $depth, $args = array(), $id = 0 ) {
		ob_start();
		do_action( 'wp_nav_menu_item_custom_labels', $id, $item, $depth, $args );
		return ob_get_clean();
	}
}
```

in `OS_Menu_Item_Custom_Fields` i've added that action.

```php
add_action( 'wp_nav_menu_item_custom_labels', array( __CLASS__, '_labels' ), 11, 4 );

public static function _labels( $id, $item, $depth, $args ){
	$out = '<span class="os-item-label-mega"><span class="os_label os_bg_brand">Mega Menu</span></span>';
	$out .= '<span class="os-item-label-mega-column"><span class="os_label os_bg_brand_alt">Column</span></span>';
	echo $out;
}
```

Interesting that, when i've used `wp-menu-icons` from `icon-picker-integration` branch — my `Menu_Item_Custom_Fields_Walker` class was not overridden by plugin's class.

So, I have a question. How to right filter `Walker_Nav_Menu_Edit` walker via your `Menu_Item_Custom_Fields_Walker` from this library that in the future do not have problems with other plug-ins, which can also extend `Walker_Nav_Menu_Edit` walker class?

Cheers!

**Comment by kucrut** [comment]
Please take a look here: https://github.com/kucrut/wp-menu-icons/blob/develop/includes/picker.php#L51

In short, you should only include the custom walker class from your `wp_edit_nav_menu_walker` filter callback if the class doesn't exist yet.

**Comment by kucrut** [comment]
Also, make sure to hook into `wp_edit_nav_menu_walker` **after priority 99** which Menu Icons uses.

**Comment by vburlak** [comment]
@kucrut exactly!
That's just what I need!

I also previously tried to add prefixes to my menu item custom fields classes in order to prevent further conflict. And altogether forgot about filter priority. Thanks a lot!
