### ISSUE TITLE
Doesn't work in WordPress 4.7

### ISSUE THREAD

**Issue by rahulnever2far** [kucrut/wp-menu-item-custom-fields#7]
This works fine with WordPress 4.6.1 but doesn't work with WordPress 4.7. I can't seem to figure out the issue. Could you please point me in the right direction.

Thank you!

**Comment by rahulnever2far** [comment]
Submitted a pull request #8

**Comment by quangduy90** [comment]
Yes, it doesn't work in wp 4.7, can you fix, please ? :(

**Comment by quangduy90** [comment]
@rahulnever2far 
I found a solution, if you want to work in wp 4.7, open `menu-item-custom-fields/walker-nav-menu-edit.php`
Line 43, change to : `'/(?=<fieldset[^>]+class="[^"]*field-move)/',`

**Comment by rahulnever2far** [comment]
I have submitted a pull request for the same. I'm not sure when @kucrut will able to merge it.

**Comment by kucrut** [comment]
Fixed via #8.
